/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.sparrow.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StateStoreService {

  public interface Iface {

    public void registerScheduler(String schedulerAddress) throws org.apache.thrift.TException;

    public void registerNodeMonitor(String nodeMonitorAddress) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void registerScheduler(String schedulerAddress, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.registerScheduler_call> resultHandler) throws org.apache.thrift.TException;

    public void registerNodeMonitor(String nodeMonitorAddress, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.registerNodeMonitor_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void registerScheduler(String schedulerAddress) throws org.apache.thrift.TException
    {
      send_registerScheduler(schedulerAddress);
      recv_registerScheduler();
    }

    public void send_registerScheduler(String schedulerAddress) throws org.apache.thrift.TException
    {
      registerScheduler_args args = new registerScheduler_args();
      args.setSchedulerAddress(schedulerAddress);
      sendBase("registerScheduler", args);
    }

    public void recv_registerScheduler() throws org.apache.thrift.TException
    {
      registerScheduler_result result = new registerScheduler_result();
      receiveBase(result, "registerScheduler");
      return;
    }

    public void registerNodeMonitor(String nodeMonitorAddress) throws org.apache.thrift.TException
    {
      send_registerNodeMonitor(nodeMonitorAddress);
      recv_registerNodeMonitor();
    }

    public void send_registerNodeMonitor(String nodeMonitorAddress) throws org.apache.thrift.TException
    {
      registerNodeMonitor_args args = new registerNodeMonitor_args();
      args.setNodeMonitorAddress(nodeMonitorAddress);
      sendBase("registerNodeMonitor", args);
    }

    public void recv_registerNodeMonitor() throws org.apache.thrift.TException
    {
      registerNodeMonitor_result result = new registerNodeMonitor_result();
      receiveBase(result, "registerNodeMonitor");
      return;
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void registerScheduler(String schedulerAddress, org.apache.thrift.async.AsyncMethodCallback<registerScheduler_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      registerScheduler_call method_call = new registerScheduler_call(schedulerAddress, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class registerScheduler_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String schedulerAddress;
      public registerScheduler_call(String schedulerAddress, org.apache.thrift.async.AsyncMethodCallback<registerScheduler_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.schedulerAddress = schedulerAddress;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("registerScheduler", org.apache.thrift.protocol.TMessageType.CALL, 0));
        registerScheduler_args args = new registerScheduler_args();
        args.setSchedulerAddress(schedulerAddress);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        (new Client(prot)).recv_registerScheduler();
      }
    }

    public void registerNodeMonitor(String nodeMonitorAddress, org.apache.thrift.async.AsyncMethodCallback<registerNodeMonitor_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      registerNodeMonitor_call method_call = new registerNodeMonitor_call(nodeMonitorAddress, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class registerNodeMonitor_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String nodeMonitorAddress;
      public registerNodeMonitor_call(String nodeMonitorAddress, org.apache.thrift.async.AsyncMethodCallback<registerNodeMonitor_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.nodeMonitorAddress = nodeMonitorAddress;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("registerNodeMonitor", org.apache.thrift.protocol.TMessageType.CALL, 0));
        registerNodeMonitor_args args = new registerNodeMonitor_args();
        args.setNodeMonitorAddress(nodeMonitorAddress);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        (new Client(prot)).recv_registerNodeMonitor();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("registerScheduler", new registerScheduler());
      processMap.put("registerNodeMonitor", new registerNodeMonitor());
      return processMap;
    }

    private static class registerScheduler<I extends Iface> extends org.apache.thrift.ProcessFunction<I, registerScheduler_args> {
      public registerScheduler() {
        super("registerScheduler");
      }

      protected registerScheduler_args getEmptyArgsInstance() {
        return new registerScheduler_args();
      }

      protected registerScheduler_result getResult(I iface, registerScheduler_args args) throws org.apache.thrift.TException {
        registerScheduler_result result = new registerScheduler_result();
        iface.registerScheduler(args.schedulerAddress);
        return result;
      }
    }

    private static class registerNodeMonitor<I extends Iface> extends org.apache.thrift.ProcessFunction<I, registerNodeMonitor_args> {
      public registerNodeMonitor() {
        super("registerNodeMonitor");
      }

      protected registerNodeMonitor_args getEmptyArgsInstance() {
        return new registerNodeMonitor_args();
      }

      protected registerNodeMonitor_result getResult(I iface, registerNodeMonitor_args args) throws org.apache.thrift.TException {
        registerNodeMonitor_result result = new registerNodeMonitor_result();
        iface.registerNodeMonitor(args.nodeMonitorAddress);
        return result;
      }
    }

  }

  public static class registerScheduler_args implements org.apache.thrift.TBase<registerScheduler_args, registerScheduler_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerScheduler_args");

    private static final org.apache.thrift.protocol.TField SCHEDULER_ADDRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("schedulerAddress", org.apache.thrift.protocol.TType.STRING, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerScheduler_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerScheduler_argsTupleSchemeFactory());
    }

    public String schedulerAddress; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SCHEDULER_ADDRESS((short)1, "schedulerAddress");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // SCHEDULER_ADDRESS
            return SCHEDULER_ADDRESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SCHEDULER_ADDRESS, new org.apache.thrift.meta_data.FieldMetaData("schedulerAddress", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerScheduler_args.class, metaDataMap);
    }

    public registerScheduler_args() {
    }

    public registerScheduler_args(
      String schedulerAddress)
    {
      this();
      this.schedulerAddress = schedulerAddress;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerScheduler_args(registerScheduler_args other) {
      if (other.isSetSchedulerAddress()) {
        this.schedulerAddress = other.schedulerAddress;
      }
    }

    public registerScheduler_args deepCopy() {
      return new registerScheduler_args(this);
    }

    public void clear() {
      this.schedulerAddress = null;
    }

    public String getSchedulerAddress() {
      return this.schedulerAddress;
    }

    public registerScheduler_args setSchedulerAddress(String schedulerAddress) {
      this.schedulerAddress = schedulerAddress;
      return this;
    }

    public void unsetSchedulerAddress() {
      this.schedulerAddress = null;
    }

    /** Returns true if field schedulerAddress is set (has been assigned a value) and false otherwise */
    public boolean isSetSchedulerAddress() {
      return this.schedulerAddress != null;
    }

    public void setSchedulerAddressIsSet(boolean value) {
      if (!value) {
        this.schedulerAddress = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SCHEDULER_ADDRESS:
        if (value == null) {
          unsetSchedulerAddress();
        } else {
          setSchedulerAddress((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SCHEDULER_ADDRESS:
        return getSchedulerAddress();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SCHEDULER_ADDRESS:
        return isSetSchedulerAddress();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerScheduler_args)
        return this.equals((registerScheduler_args)that);
      return false;
    }

    public boolean equals(registerScheduler_args that) {
      if (that == null)
        return false;

      boolean this_present_schedulerAddress = true && this.isSetSchedulerAddress();
      boolean that_present_schedulerAddress = true && that.isSetSchedulerAddress();
      if (this_present_schedulerAddress || that_present_schedulerAddress) {
        if (!(this_present_schedulerAddress && that_present_schedulerAddress))
          return false;
        if (!this.schedulerAddress.equals(that.schedulerAddress))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerScheduler_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerScheduler_args typedOther = (registerScheduler_args)other;

      lastComparison = Boolean.valueOf(isSetSchedulerAddress()).compareTo(typedOther.isSetSchedulerAddress());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSchedulerAddress()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.schedulerAddress, typedOther.schedulerAddress);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerScheduler_args(");
      boolean first = true;

      sb.append("schedulerAddress:");
      if (this.schedulerAddress == null) {
        sb.append("null");
      } else {
        sb.append(this.schedulerAddress);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private static class registerScheduler_argsStandardSchemeFactory implements SchemeFactory {
      public registerScheduler_argsStandardScheme getScheme() {
        return new registerScheduler_argsStandardScheme();
      }
    }

    private static class registerScheduler_argsStandardScheme extends StandardScheme<registerScheduler_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerScheduler_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // SCHEDULER_ADDRESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.schedulerAddress = iprot.readString();
                struct.setSchedulerAddressIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerScheduler_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.schedulerAddress != null) {
          oprot.writeFieldBegin(SCHEDULER_ADDRESS_FIELD_DESC);
          oprot.writeString(struct.schedulerAddress);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerScheduler_argsTupleSchemeFactory implements SchemeFactory {
      public registerScheduler_argsTupleScheme getScheme() {
        return new registerScheduler_argsTupleScheme();
      }
    }

    private static class registerScheduler_argsTupleScheme extends TupleScheme<registerScheduler_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerScheduler_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSchedulerAddress()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSchedulerAddress()) {
          oprot.writeString(struct.schedulerAddress);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerScheduler_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.schedulerAddress = iprot.readString();
          struct.setSchedulerAddressIsSet(true);
        }
      }
    }

  }

  public static class registerScheduler_result implements org.apache.thrift.TBase<registerScheduler_result, registerScheduler_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerScheduler_result");


    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerScheduler_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerScheduler_resultTupleSchemeFactory());
    }


    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
;

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerScheduler_result.class, metaDataMap);
    }

    public registerScheduler_result() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerScheduler_result(registerScheduler_result other) {
    }

    public registerScheduler_result deepCopy() {
      return new registerScheduler_result(this);
    }

    public void clear() {
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerScheduler_result)
        return this.equals((registerScheduler_result)that);
      return false;
    }

    public boolean equals(registerScheduler_result that) {
      if (that == null)
        return false;

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerScheduler_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerScheduler_result typedOther = (registerScheduler_result)other;

      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerScheduler_result(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private static class registerScheduler_resultStandardSchemeFactory implements SchemeFactory {
      public registerScheduler_resultStandardScheme getScheme() {
        return new registerScheduler_resultStandardScheme();
      }
    }

    private static class registerScheduler_resultStandardScheme extends StandardScheme<registerScheduler_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerScheduler_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerScheduler_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerScheduler_resultTupleSchemeFactory implements SchemeFactory {
      public registerScheduler_resultTupleScheme getScheme() {
        return new registerScheduler_resultTupleScheme();
      }
    }

    private static class registerScheduler_resultTupleScheme extends TupleScheme<registerScheduler_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerScheduler_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerScheduler_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
      }
    }

  }

  public static class registerNodeMonitor_args implements org.apache.thrift.TBase<registerNodeMonitor_args, registerNodeMonitor_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerNodeMonitor_args");

    private static final org.apache.thrift.protocol.TField NODE_MONITOR_ADDRESS_FIELD_DESC = new org.apache.thrift.protocol.TField("nodeMonitorAddress", org.apache.thrift.protocol.TType.STRING, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerNodeMonitor_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerNodeMonitor_argsTupleSchemeFactory());
    }

    public String nodeMonitorAddress; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      NODE_MONITOR_ADDRESS((short)1, "nodeMonitorAddress");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // NODE_MONITOR_ADDRESS
            return NODE_MONITOR_ADDRESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.NODE_MONITOR_ADDRESS, new org.apache.thrift.meta_data.FieldMetaData("nodeMonitorAddress", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerNodeMonitor_args.class, metaDataMap);
    }

    public registerNodeMonitor_args() {
    }

    public registerNodeMonitor_args(
      String nodeMonitorAddress)
    {
      this();
      this.nodeMonitorAddress = nodeMonitorAddress;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerNodeMonitor_args(registerNodeMonitor_args other) {
      if (other.isSetNodeMonitorAddress()) {
        this.nodeMonitorAddress = other.nodeMonitorAddress;
      }
    }

    public registerNodeMonitor_args deepCopy() {
      return new registerNodeMonitor_args(this);
    }

    public void clear() {
      this.nodeMonitorAddress = null;
    }

    public String getNodeMonitorAddress() {
      return this.nodeMonitorAddress;
    }

    public registerNodeMonitor_args setNodeMonitorAddress(String nodeMonitorAddress) {
      this.nodeMonitorAddress = nodeMonitorAddress;
      return this;
    }

    public void unsetNodeMonitorAddress() {
      this.nodeMonitorAddress = null;
    }

    /** Returns true if field nodeMonitorAddress is set (has been assigned a value) and false otherwise */
    public boolean isSetNodeMonitorAddress() {
      return this.nodeMonitorAddress != null;
    }

    public void setNodeMonitorAddressIsSet(boolean value) {
      if (!value) {
        this.nodeMonitorAddress = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case NODE_MONITOR_ADDRESS:
        if (value == null) {
          unsetNodeMonitorAddress();
        } else {
          setNodeMonitorAddress((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case NODE_MONITOR_ADDRESS:
        return getNodeMonitorAddress();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case NODE_MONITOR_ADDRESS:
        return isSetNodeMonitorAddress();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerNodeMonitor_args)
        return this.equals((registerNodeMonitor_args)that);
      return false;
    }

    public boolean equals(registerNodeMonitor_args that) {
      if (that == null)
        return false;

      boolean this_present_nodeMonitorAddress = true && this.isSetNodeMonitorAddress();
      boolean that_present_nodeMonitorAddress = true && that.isSetNodeMonitorAddress();
      if (this_present_nodeMonitorAddress || that_present_nodeMonitorAddress) {
        if (!(this_present_nodeMonitorAddress && that_present_nodeMonitorAddress))
          return false;
        if (!this.nodeMonitorAddress.equals(that.nodeMonitorAddress))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerNodeMonitor_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerNodeMonitor_args typedOther = (registerNodeMonitor_args)other;

      lastComparison = Boolean.valueOf(isSetNodeMonitorAddress()).compareTo(typedOther.isSetNodeMonitorAddress());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetNodeMonitorAddress()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nodeMonitorAddress, typedOther.nodeMonitorAddress);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerNodeMonitor_args(");
      boolean first = true;

      sb.append("nodeMonitorAddress:");
      if (this.nodeMonitorAddress == null) {
        sb.append("null");
      } else {
        sb.append(this.nodeMonitorAddress);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private static class registerNodeMonitor_argsStandardSchemeFactory implements SchemeFactory {
      public registerNodeMonitor_argsStandardScheme getScheme() {
        return new registerNodeMonitor_argsStandardScheme();
      }
    }

    private static class registerNodeMonitor_argsStandardScheme extends StandardScheme<registerNodeMonitor_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerNodeMonitor_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // NODE_MONITOR_ADDRESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.nodeMonitorAddress = iprot.readString();
                struct.setNodeMonitorAddressIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerNodeMonitor_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.nodeMonitorAddress != null) {
          oprot.writeFieldBegin(NODE_MONITOR_ADDRESS_FIELD_DESC);
          oprot.writeString(struct.nodeMonitorAddress);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerNodeMonitor_argsTupleSchemeFactory implements SchemeFactory {
      public registerNodeMonitor_argsTupleScheme getScheme() {
        return new registerNodeMonitor_argsTupleScheme();
      }
    }

    private static class registerNodeMonitor_argsTupleScheme extends TupleScheme<registerNodeMonitor_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerNodeMonitor_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetNodeMonitorAddress()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetNodeMonitorAddress()) {
          oprot.writeString(struct.nodeMonitorAddress);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerNodeMonitor_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.nodeMonitorAddress = iprot.readString();
          struct.setNodeMonitorAddressIsSet(true);
        }
      }
    }

  }

  public static class registerNodeMonitor_result implements org.apache.thrift.TBase<registerNodeMonitor_result, registerNodeMonitor_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerNodeMonitor_result");


    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerNodeMonitor_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerNodeMonitor_resultTupleSchemeFactory());
    }


    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
;

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerNodeMonitor_result.class, metaDataMap);
    }

    public registerNodeMonitor_result() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerNodeMonitor_result(registerNodeMonitor_result other) {
    }

    public registerNodeMonitor_result deepCopy() {
      return new registerNodeMonitor_result(this);
    }

    public void clear() {
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerNodeMonitor_result)
        return this.equals((registerNodeMonitor_result)that);
      return false;
    }

    public boolean equals(registerNodeMonitor_result that) {
      if (that == null)
        return false;

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(registerNodeMonitor_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      registerNodeMonitor_result typedOther = (registerNodeMonitor_result)other;

      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerNodeMonitor_result(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te.getMessage());
      }
    }

    private static class registerNodeMonitor_resultStandardSchemeFactory implements SchemeFactory {
      public registerNodeMonitor_resultStandardScheme getScheme() {
        return new registerNodeMonitor_resultStandardScheme();
      }
    }

    private static class registerNodeMonitor_resultStandardScheme extends StandardScheme<registerNodeMonitor_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerNodeMonitor_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerNodeMonitor_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerNodeMonitor_resultTupleSchemeFactory implements SchemeFactory {
      public registerNodeMonitor_resultTupleScheme getScheme() {
        return new registerNodeMonitor_resultTupleScheme();
      }
    }

    private static class registerNodeMonitor_resultTupleScheme extends TupleScheme<registerNodeMonitor_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerNodeMonitor_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerNodeMonitor_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
      }
    }

  }

}
